<?php
//Auto-generated by PHPue Matrix CMS on 2026-06-08
return [
    'title' => 'Why We Built a Database-Free CMS Template',
    'slug' => 'tpl-why-we-built-a-database-free-cms-template',
    'theme' => 'default',
    'status' => 'draft',
    'created' => '2026-06-08',
    'sections' => array (
  0 => 
  array (
    'type' => 'hero',
    'data' => 
    array (
      'heading' => 'Why We Built a Database-Free CMS',
      'subheading' => 'WordPress runs 43% of the web. It also runs 60 database queries to serve a blog post. We asked: what if the filesystem WAS the database?',
      'bg_image' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1920&q=80',
      'cta_text' => 'Read the Story',
      'cta_url' => '#story',
    ),
  ),
  1 => 
  array (
    'type' => 'content',
    'data' => 
    array (
      'heading' => 'The Problem With Modern CMSs',
      'body' => 'Let\'s be honest: most websites don\'t need a database.

A restaurant menu. A blog. A portfolio. A landing page. These are documents. They change infrequently. They\'re read frequently. Yet the industry standard is to store them in MySQL, wrap them in an ORM, cache them in Redis, and serve them through a PHP framework that boots on every request.

That\'s not engineering. That\'s ritual.

We built PHPue Matrix to ask a simple question: what if content was just a PHP file?',
    ),
  ),
  2 => 
  array (
    'type' => 'pull-quote',
    'data' => 
    array (
      'quote' => 'The filesystem is the original database. It\'s fast, it\'s reliable, and it doesn\'t need a connection pool.',
      'author' => 'Edward Patch',
      'author_title' => 'Creator, PHPue Matrix',
    ),
  ),
  3 => 
  array (
    'type' => 'content-wide',
    'data' => 
    array (
      'heading' => 'How It Works',
      'body' => '<strong>1. Content is a PHP array.</strong> Not JSON. Not YAML. Not Markdown-in-a-database. A native PHP array that returns from an include.

<strong>2. Themes are closures.</strong> Each section type has a render function. Pass it data, get back HTML. No template engine. No Blade. No Twig. Just PHP doing what PHP does.

<strong>3. OpCache makes it sub-1ms.</strong> PHP compiles the file once, caches the bytecode in memory, and serves it faster than any database query could ever hope to.

<strong>4. Zero dependencies.</strong> No Composer. No npm. No webpack. Just FTP the files and go.',
      'bg_color' => '',
    ),
  ),
  4 => 
  array (
    'type' => 'divider',
    'data' => 
    array (
    ),
  ),
  5 => 
  array (
    'type' => 'split-image-text',
    'data' => 
    array (
      'heading' => 'The Admin Panel',
      'body' => 'We built a full admin UI — also without a database. It reads theme definitions to know what fields to show, lets you add and remove sections dynamically, and saves everything as a clean PHP file.

No migrations. No schema changes. No "white screen of death" because a plugin updated. Just a form that writes a file.

The admin itself is built in PHPue — our own framework. It uses the same .pvue component system, the same @AJAX decorators, and the same flat-file philosophy.',
      'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
      'image_position' => 'right',
    ),
  ),
  6 => 
  array (
    'type' => 'full-width-image',
    'data' => 
    array (
      'image' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1920&q=80',
      'alt_text' => 'Clean code on a screen',
      'caption' => 'Clean, simple, fast. No database. No build step. Just PHP.',
    ),
  ),
  7 => 
  array (
    'type' => 'card-grid-3',
    'data' => 
    array (
      'heading' => 'What Makes It Different',
      'card1_title' => 'Flat-File Storage',
      'card1_body' => 'Content lives in .php files that return arrays. Version control with Git. Deploy with FTP. No database to migrate, backup, or corrupt.',
      'card1_icon' => 'fa-solid fa-file-code',
      'card2_title' => 'Theme Engine',
      'card2_body' => 'Themes are PHP files that register section types and render closures. Add a section type — the admin UI updates automatically.',
      'card2_icon' => 'fa-solid fa-palette',
      'card3_title' => 'Sub-Millisecond',
      'card3_body' => 'OpCache compiles your content once and serves from memory. No query builder. No ORM hydration. Just include, render, done.',
      'card3_icon' => 'fa-solid fa-bolt',
    ),
  ),
  8 => 
  array (
    'type' => 'content',
    'data' => 
    array (
      'heading' => 'The Philosophy',
      'body' => 'We\'re not saying databases are bad. We\'re saying not everything needs one.

PHPue Matrix is for the 80% of websites that are fundamentally documents with a design wrapped around them. For those sites, a database is overhead — mental, operational, and computational.

By treating content as code (PHP arrays), we get version control for free. By treating themes as closures, we get infinite flexibility without a template language. By treating the filesystem as the data store, we get simplicity that no ORM can match.

This is PHP the way it was meant to be: fast, simple, and direct.',
    ),
  ),
  9 => 
  array (
    'type' => 'cta',
    'data' => 
    array (
      'heading' => 'Try PHPue Matrix Today',
      'subheading' => 'Open source. Zero dependencies. Five lines to your first page.',
      'button_text' => 'View on GitHub',
      'button_url' => 'https://github.com/PHPue/PHPue-Extensions',
    ),
  ),
  10 => 
  array (
    'type' => 'author-bio',
    'data' => 
    array (
      'name' => 'Edward Patch',
      'bio' => 'Full-stack developer and creator of PHPue. Based in Carmarthen, Wales. Builds tools that respect the server and the developer.',
      'avatar' => 'https://media.licdn.com/dms/image/v2/D4E03AQGA_1gj5T38ww/profile-displayphoto-crop_800_800/B4EZnkfMe2IwAI-/0/1760475007745?e=1782345600&v=beta&t=8oju07_FwLfbDHLElMQedMyJFLwUZuY-qJ7qWt1pNqs',
      'social_website' => 'https://phpue.com',
    ),
  ),
  11 => 
  array (
    'type' => 'related-posts',
    'data' => 
    array (
      'heading' => 'More From Our Blog',
      'count' => '2',
    ),
  ),
),
];