<?php 
    /* Author(s): Edward Patch */
    namespace PHPueExt;

    if (defined('PHPUE_VERSION') && version_compare(PHPUE_VERSION, '0.0.2', '>=')) {
        class PHPueMatrix
        {
            private static ?self $instance = null;
            private static string $themesDir;
            private static string $pagesDir;
            public static array $phpueLang;

            private function __construct() {
                self::$themesDir = __DIR__ . '/themes';
                self::$pagesDir  = __DIR__ . '/pages';

                self::$phpueLang = [
                    'hero' => "Hello"
                ];

            }

            public static function getInstance(): self {
                if(self::$instance === null)
                    self::$instance = new self();

                return self::$instance;
            }

            // ─────────────────────────────────────────────
            // getPage($slug) → Renders a full page from stored data + theme
            // ─────────────────────────────────────────────
           public static function getPage(string $route, string $slug): string {
                $inst = self::getInstance();
                $pagePath = self::$pagesDir . "/{$route}/{$slug}.php";

                if(!file_exists($pagePath)) return '';

                $pageData = include $pagePath;

                $themeName = $pageData['theme'] ?? 'default';
                $themePath = self::$themesDir . "/{$themeName}.php";

                if(!file_exists($themePath)) return '<p>Theme not found.</p>';

                $theme = include $themePath;
                $sectionRenderers = $theme['sections'];

                $html = '';
                foreach($pageData['sections'] as $section) {
                    $type = $section['type'];
                    $data = $section['data'];

                    if(isset($sectionRenderers[$type]['render']))
                        $html .= $sectionRenderers[$type]['render']($data);
                }

          
                $shortcodes = $theme['shortcodes'] ?? [];
                $html = self::parseShortcodes($html, $shortcodes);
        
                return $html;
            }

            // ─────────────────────────────────────────────
            // getPagePreview() → Returns raw HTML for preview iframe
            // ─────────────────────────────────────────────
            public static function getPagePreview(string $route, string $slug): string
            {
                return self::getPage($route, $slug);
            }

            // ─────────────────────────────────────────────
            // createPage($slug, $theme, $sections) → Writes page data to disk
            // ─────────────────────────────────────────────
            public static function createPage(string $route, string $slug, string $theme, array $sections, string $title = '', string $status = 'live'): bool
            {
                $inst = self::getInstance();
                $dir = self::$pagesDir.'/'.$route;

                if(!is_dir($dir))
                    mkdir($dir, 0755, true);

                $filePath = "{$dir}/{$slug}.php";

                // Build the PHP array source code
                $date = date('Y-m-d');
                $exportSections = var_export($sections, true);
                $titleSafe = addslashes($title);
                $slugSafe = addslashes($slug);
                $themeSafe = addslashes($theme);
                $statusSafe = addslashes($status);

                $content = <<<PHP
                <?php
                //Auto-generated by PHPue Matrix CMS on {$date}
                return [
                    'title' => '{$titleSafe}',
                    'slug' => '{$slugSafe}',
                    'theme' => '{$themeSafe}',
                    'status' => '{$statusSafe}',
                    'created' => '{$date}',
                    'sections' => {$exportSections},
                ];
                PHP;

               $written = file_put_contents($filePath, $content) !== false;
    
                // Invalidate OpCache for this file so next include gets fresh data
                if ($written && function_exists('opcache_invalidate')) {
                    opcache_invalidate($filePath, true);
                }
                
                return $written;
            }

            // ─────────────────────────────────────────────
            // getTheme($name) → Returns the theme registry (for the admin UI)
            // ─────────────────────────────────────────────
            public static function getTheme(string $name = 'default'): array
            {
                $inst = self::getInstance();
                $themePath = self::$themesDir . "/{$name}.php";

                if(!file_exists($themePath))
                    return [];

                $theme = include $themePath;

                // Return only the metadata + field definitions (not closures) for the admin
                $result = [
                    'meta' => $theme['meta'] ?? [],
                    'sections' => []
                ];

                foreach($theme['sections'] as $type => $def)
                    {
                        $result['sections'][$type] = [
                            'label' => $def['label'],
                            'fields' => $def['fields']
                        ];
                    }

                return $result;
            }

            // ─────────────────────────────────────────────
            // listPages() → Scans pages/ dir for admin listing
            // ─────────────────────────────────────────────
            public static function listPages(string $category = 'blogs'): array
            {
                $inst = self::getInstance();
                $dir = self::$pagesDir . '/' . $category;

                if(!is_dir($dir))
                    return [];

                $pages = [];
                foreach(glob("{$dir}/*.php") as $file) {
                    // Invalidate OpCache for each page file
                    if (function_exists('opcache_invalidate')) {
                        opcache_invalidate($file, true);
                    }
                    
                    $data = include $file;
                    $pages[] = [
                        'slug' => $data['slug'] ?? basename($file, '.php'),
                        'title' => $data['title'] ?? 'Untitled',
                        'status' => $data['status'] ?? 'draft',
                        'created' => $data['created'] ?? 'unknown',
                    ];
                }

                return $pages;
            }

            // ─────────────────────────────────────────────
            // deletePage() → Removes a page file from disk
            // ─────────────────────────────────────────────
            public static function deletePage(string $route, string $slug): bool
            {
                $inst = self::getInstance();
                $filePath = self::$pagesDir . "/{$route}/{$slug}.php";
                
                if (!file_exists($filePath)) {
                    return false;
                }
                
                // Invalidate OpCache before deleting
                if (function_exists('opcache_invalidate')) {
                    opcache_invalidate($filePath, true);
                }
                
                return unlink($filePath);
            }

            // ─────────────────────────────────────────────
            // listRoutes() → Scans pages/ dir for all route folders
            // ─────────────────────────────────────────────
            public static function listRoutes(): array
            {
                $inst = self::getInstance();
                $dir = self::$pagesDir;
                
                if (!is_dir($dir)) {
                    return [];
                }
                
                $routes = [];
                foreach (glob($dir . '/*', GLOB_ONLYDIR) as $routeDir) {
                    $routeName = basename($routeDir);
                    $pageCount = count(glob($routeDir . '/*.php'));
                    $routes[$routeName] = [
                        'name' => $routeName,
                        'count' => $pageCount,
                    ];
                }
                
                ksort($routes);
                return $routes;
            }

            // ─────────────────────────────────────────────
            // parseShortcodes() → Resolves [[token]] and [[namespace.key]] patterns
            // ─────────────────────────────────────────────
            private static function parseShortcodes(string $html, array $shortcodes): string
            {
                return preg_replace_callback('/\[\[(\S+?)\]\]/', function($matches) use ($shortcodes) {
                    $token = $matches[1];
                    
                    // Check for dot notation: phpueLang.hero_welcome
                    if (str_contains($token, '.')) {
                        [$namespace, $key] = explode('.', $token, 2);
                        if (isset($shortcodes[$namespace]) && is_callable($shortcodes[$namespace])) {
                            $result = $shortcodes[$namespace]($key);
                            return is_string($result) || is_numeric($result) ? (string) $result : $matches[0];
                        }
                    }
                    
                    // Exact match shortcode: [[year]]
                    if (isset($shortcodes[$token]) && is_callable($shortcodes[$token])) {
                        $result = $shortcodes[$token]();
                        return is_string($result) || is_numeric($result) ? (string) $result : $matches[0];
                    }
                    
                    return $matches[0]; // Unresolved — leave visible for debugging
                }, $html);
            }
        }
    }

?>